name: Build and Test
on:
  push:
  pull_request:
    branches:
    - 'main'
  workflow_dispatch:
defaults:
  run:
    shell: bash
jobs:
  build:
    name: Build Telescope 🔭
    runs-on: ubuntu-latest
    steps:
    - name: 🏁 Checkout
      uses: actions/checkout@v3
      with:
        submodules: 'true'
    - name: 🧱 Install build dependencies
      run: |        
        sudo aptitude install libglm-dev libvulkan-dev libsdl2-dev libsdl2-image-dev libsdl2-mixer-dev libbox2d-dev
    - name: 🦏 Build
      run: |
        mkdir build && cd build
        cmake .. -DCMAKE_INSTALL_PREFIX=..
        make clean && make install
    - name: 🧪 Unit tests
      run: echo noop #cd build && make test ARGS="-N" && make test ARGS="-V"
    # Only upload the build if this is a push to _Main_ or a dispatch (PRs shouldn't need this, they only need the above test)
    - name: 🆙 Upload compiled source
      if: ${{ (github.event_name == 'push' && github.event.ref == 'refs/heads/main') || github.event_name == 'workflow_dispatch' }}
      uses: actions/upload-artifact@v3
      with:
        name: libtelescope-pretest
        path: lib/libtelescope.so
        if-no-files-found: error
