name: Build and test
on:
  push:
  pull_request:
    branches:
    - 'main'
  workflow_dispatch:
defaults:
  run:
    shell: bash
jobs:
  build:
    name: Build telescope
    runs-on: ubuntu-latest
    steps:
    - name: 🏁 Checkout
      uses: actions/checkout@v3
      with:
        submodules: 'true'
    - name: 🧱 Install build dependencies
      run: |
        wget -qO - http://packages.lunarg.com/lunarg-signing-key-pub.asc | apt-key add -
        wget -qO /etc/apt/sources.list.d/lunarg-vulkan-focal.list http://packages.lunarg.com/vulkan/lunarg-vulkan-focal.list
        apt update && apt install --upgrade cmake
        apt install --upgrade libsdl2-dev libsdl2-image-dev libsdl2-mixer-dev libsdl2-ttf-dev libsdl2-net-dev
        apt install --upgrade vulkan-sdk
        apt install --upgrade libbullet-dev libglm-dev shaderc
    - name: 🦏 Build
      run: |
        cmake .
        make clean
        make
